server {
    listen 80;
    server_name shlenskov.pro www.shlenskov.pro;
    return 301 https://shlenskov.pro$request_uri;
}

server {
    listen 443 ssl;
    server_name shlenskov.pro www.shlenskov.pro;

    ssl_certificate     /etc/letsencrypt/live/shlenskov.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shlenskov.pro/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/landing;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # проксируем только эндпоинт формы на FastAPI
    location /send {
        proxy_pass         http://127.0.0.1:8000/send;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 10s;
    }
}
